name: smad
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - pyyaml
  - scipy
  - matplotlib
  - pytest
  - pyspark
  - pip
  - pip:
    - numpy
    - scikit-learn
    - torch
    - torchvision
