name: smad
channels:
  - defaults
dependencies:
  - arrow-cpp=21.0.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.9.9
  - cairo=1.18.4
  - colorama=0.4.6
  - contourpy=1.3.1
  - cycler=0.11.0
  - expat=2.7.1
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - gflags=2.2.2
  - glog=0.5.0
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icc_rt=2022.1.0
  - icu=73.1
  - iniconfig=2.1.0
  - intel-openmp=2025.0.0
  - jpeg=9f
  - kiwisolver=1.4.8
  - lcms2=2.16
  - lerc=3.0
  - libabseil=20250127.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.15.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libglib=2.84.2
  - libgrpc=1.71.0
  - libiconv=1.16
  - libkrb5=1.21.3
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - matplotlib=3.10.5
  - matplotlib-base=3.10.5
  - mkl=2025.0.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - numexpr=2.11.0
  - openjpeg=2.5.2
  - openssl=3.0.18
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.2
  - pcre2=10.42
  - pip=25.1
  - pixman=0.46.4
  - pluggy=1.5.0
  - py4j=0.10.9.9
  - pyarrow=21.0.0
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - pyspark=4.0.1
  - pytest=8.4.2
  - python=3.11.13
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - pyyaml=6.0.2
  - qtbase=6.9.1
  - qtdeclarative=6.9.1
  - qtsvg=6.9.1
  - qttools=6.9.1
  - qtwebchannel=6.9.1
  - qtwebsockets=6.9.1
  - re2=2024.07.02
  - setuptools=78.1.1
  - sip=6.12.0
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.50.2
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tk=8.6.15
  - tornado=6.5.1
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - utf8proc=2.6.1
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - filelock==3.13.1
      - fsspec==2024.6.1
      - jinja2==3.1.4
      - joblib==1.5.2
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.1.2
      - pillow==11.0.0
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - sympy==1.13.3
      - threadpoolctl==3.6.0
      - torch==2.8.0+cu126
      - torchvision==0.23.0+cu126
      - typing-extensions==4.12.2
